"use strict";

/*
 * Zero-dependency build step for the static frontend (Vercel).
 *
 * Generates `api-config.js` in this directory from the VITE_API_URL
 * environment variable so app.js knows which Render backend to call.
 *
 *   VITE_API_URL=https://<your-render-service>.onrender.com  ->  production
 *   (unset)                                                  ->  http://localhost:8000 (local dev)
 *
 * Run with `node build.js` (Vercel runs this via frontend/vercel.json).
 */

const fs = require("fs");
const path = require("path");

const apiUrl = process.env.VITE_API_URL || "http://localhost:8000";

if (process.env.VERCEL && !process.env.VITE_API_URL) {
  console.warn(
    "build warning: VITE_API_URL is not set; the deployed frontend will call " +
      "http://localhost:8000. Set VITE_API_URL in the Vercel project settings."
  );
}

const outFile = path.join(__dirname, "api-config.js");
const content =
  "/* Generated by build.js. Do not edit. */\n" +
  "window.SENTIMENT_API_BASE = " + JSON.stringify(apiUrl) + ";\n";

fs.writeFileSync(outFile, content, "utf8");
console.log("generated " + outFile + " -> " + apiUrl);